use strict;
use warnings FATAL => 'all';
use Cwd qw(abs_path);
use FindBin;
use IPC::Run;
use JSON::PP qw(decode_json);
use PostgreSQL::Test::Cluster;
use PostgreSQL::Test::Utils;
use Test::More;
use Time::HiRes qw(sleep);

my $node=PostgreSQL::Test::Cluster->new('total_budget');
$node->init;
$node->append_conf('postgresql.conf',"shared_preload_libraries='semloom_pg'\n");
$node->start;
$node->safe_psql('postgres',q{
CREATE EXTENSION semloom_pg;
CREATE TABLE heterogeneous(id integer, body text);
INSERT INTO heterogeneous SELECT g,CASE WHEN g=1 THEN 'slow' WHEN g=2 THEN 'fast' ELSE repeat('x',55000) END FROM generate_series(1,10) g;
CREATE TABLE invalid(id integer,body text);
INSERT INTO invalid VALUES(1,repeat('z',15000000));
CREATE TABLE demand(id integer,body text);
INSERT INTO demand VALUES(1,'one'),(2,repeat('z',15000000));
CREATE TABLE boundary(id integer,body text);
INSERT INTO boundary VALUES(1,'max-output');
CREATE TABLE alone(id integer,body text);
INSERT INTO alone VALUES(1,repeat('a',150000));
CREATE SEQUENCE calls;
CREATE FUNCTION touch(x text) RETURNS text LANGUAGE plpgsql VOLATILE STRICT AS
$$BEGIN PERFORM nextval('calls');RETURN x;END$$;
});
my $socket=$node->host.'/total.sock';
my $events=$node->basedir.'/events.jsonl';
my $script=abs_path("$FindBin::RealBin/fixtures/incremental_gateway.py");
my ($out,$err)=('','');
my $gateway;
END {my $status=$?;eval {$gateway->kill_kill} if defined $gateway;$?=$status;}
$gateway=IPC::Run::start(['python3',$script,'--socket',$socket,'--events',$events,'--test-output-boundaries'],'>',\$out,'2>',\$err,IPC::Run::timeout(90));
for(1..500){last if -S $socket;sleep(.01);}
ok(-S $socket,'bounded fixture is ready') or die $err;
my $settings="SET statement_timeout='10s';SET semloom_pg.gateway_socket='$socket';SET semloom_pg.provider_execution_profile='incremental-map';SET semloom_pg.provider_window_bytes=1048576;";
my $map=q|ai_semantic.map(body,'Echo.','{"model":"model","temperature":0,"max_tokens":128}'::jsonb)|;
my $query="SELECT id,$map FROM heterogeneous";
my $small=$node->safe_psql('postgres',"$settings SET semloom_pg.provider_window_tasks=2;$query");
is(scalar(split /\n/,$small),10,'legacy small window accepts these legal inputs');
my ($status,undef,$error)=$node->psql('postgres',"$settings SET semloom_pg.provider_window_tasks=8;$query");
isnt($status,0,'legacy larger window rejects a legal row under the same total budget');
like($error,qr/window byte reservation/,'legacy failure is its equal-share reservation');
my $total="$settings SET semloom_pg.enable_total_window_budget=on;SET semloom_pg.provider_staging_bytes=4194304;SET semloom_pg.test_window_memory=on;";
is($node->safe_psql('postgres',"SHOW semloom_pg.enable_total_window_budget"),'off','total policy stays opt-in');
my $large=$node->safe_psql('postgres',"$total SET semloom_pg.provider_window_tasks=8;$query");
ok($large eq $small,'total budget completes the larger window without changing a byte');
my $plan=decode_json($node->safe_psql('postgres',"$total SET semloom_pg.provider_window_tasks=8;EXPLAIN(ANALYZE,FORMAT JSON) $query"));
sub find_memory_node {
    my($node)=@_;
    return $node if exists $node->{'Semantic Retained Byte Limit'};
    for my $child(@{$node->{Plans}//[]}) {my $found=find_memory_node($child);return $found if defined $found;}
    return undef;
}
my $memory=find_memory_node($plan->[0]->{Plan});
ok(defined $memory,'EXPLAIN identifies the single-operator memory policy');
ok($memory->{'Semantic Peak Retained Bytes'}<=1048576,'actual retained contexts stay within B');
ok($memory->{'Semantic Peak Staging Bytes'}<=4194304,'pending row has an independent bounded allocation');
ok($memory->{'Semantic Peak Conversion Bytes'}<=1048576,'conversion is separately bounded');
ok($memory->{'Semantic Memory Waits'}>0,'a legal pending row waits for consumer release');
ok($memory->{'Semantic Memory Waits'}<=10,'result receipt cannot repeatedly retry unchanged retained storage');
ok($memory->{'Semantic Peak Retained Rows'}<8,'byte capacity reduces the effective row window');
sub starts {return scalar(grep {/"event": "model_start"/} split /\n/,(-e $events?slurp_file($events):''));}
my $before=starts();
is($node->safe_psql('postgres',"$total SELECT id,$map FROM invalid LIMIT 0"),'','LIMIT zero never materializes the oversized input');
is($node->safe_psql('postgres',"$total SELECT id,$map FROM demand LIMIT 1"),'1|mapped:one','LIMIT one never stages the later oversized row');
is(starts(),$before+1,'strict demand adds exactly one model request');
my $volatile=$map;$volatile=~s/map\(body/map(touch(body)/;
is($node->safe_psql('postgres',"$total SELECT $volatile FROM demand LIMIT 1"),'mapped:one','volatile fallback keeps demand semantics');
is($node->safe_psql('postgres','SELECT last_value FROM calls'),'1','input expression is evaluated once');
$before=starts();
($status,undef,$error)=$node->psql('postgres',"$total SELECT $map FROM invalid");
isnt($status,0,'compressed oversized input is rejected');
is(starts(),$before,'oversized input is rejected before external submission');
($status,undef,$error)=$node->psql('postgres',"$total SET semloom_pg.provider_staging_bytes=65536;SELECT $map FROM demand LIMIT 1");
isnt($status,0,'insufficient temporary capacity is explicit');
like($error,qr/staging byte limit/,'temporary failure names its own budget');
is(starts(),$before,'staging failure cannot spend a model request');
($status,undef,$error)=$node->psql('postgres',"$total SET semloom_pg.provider_window_tasks=1400;SELECT $map FROM alone");
isnt($status,0,'a row that cannot coexist with declared association metadata fails');
like($error,qr/cannot fit alone in total byte budget/,'permanent total-budget incompatibility is explicit');
is(starts(),$before,'an impossible single-row reservation never waits on or invokes a provider');
my $maximum=$node->safe_psql('postgres',"$total SELECT $map FROM boundary");
is(length($maximum),65536,'the maximum valid result fits its preallocated buffer exactly');
$node->safe_psql('postgres',"UPDATE boundary SET body='oversized-output'");
($status,undef,$error)=$node->psql('postgres',"$total SELECT $map FROM boundary");
isnt($status,0,'one byte beyond the output bound fails before storing a result');
$node->safe_psql('postgres',"UPDATE boundary SET body=NULL");
$before=starts();
is($node->safe_psql('postgres',"$total SELECT id,$map FROM boundary"),'1|','NULL keeps its row and has no result allocation');
is(starts(),$before,'NULL adds no model request');
$node->safe_psql('postgres',"UPDATE heterogeneous SET body='cancel' WHERE id=1");
($status,undef,$error)=$node->psql('postgres',"$total SET statement_timeout='80ms';SET semloom_pg.provider_window_tasks=8;$query");
isnt($status,0,'cancellation interrupts a full window and a pending row');
like($error,qr/canceling statement due to statement timeout/,'PostgreSQL owns cancellation');
sleep(.5);
is($node->safe_psql('postgres',"$total SELECT id,$map FROM demand LIMIT 1"),'1|mapped:one','the same gateway serves a query after cancellation');
$gateway->signal('TERM');
ok(eval {$gateway->finish},'gateway closes') or diag($err);
my @events=map {decode_json($_)} split /\n/,slurp_file($events);
my @drained=grep {$_->{event} eq 'job_drained'} @events;
ok(!scalar(grep {my $sum=0;$sum+=$_ for values %{$_->{usage}};$sum!=0} @drained),'successful and failed jobs release all core responsibilities');
my @memory_events=map {decode_json($_)} (slurp_file($node->logfile)=~/SEMLOOM_WINDOW_MEMORY (\{[^\n]+\})/g);
ok(@memory_events>=7,'memory cleanup evidence survives success, rejection and cancellation');
ok(!scalar(grep {$_->{retained_rows} || $_->{pending_rows} || $_->{retained_bytes}} @memory_events),'cleanup leaves no retained or pending row responsibility');
$node->stop;
done_testing();
