"""Version-five Map compatibility surface; common validation lives in map_codec."""

from .map_codec import (
    OpenContext as OpenContext,
    semantic_spec_digest as semantic_spec_digest,
    physical_algorithm_digest as physical_algorithm_digest,
    provider_execution_digest as provider_execution_digest,
    semantic_payload_digest as semantic_payload_digest,
    completion_evidence_digest as completion_evidence_digest,
    build_open_message as build_open_message,
    build_task_message as build_task_message,
    validate_open as validate_open,
    decimal_uint64 as decimal_uint64,
    validate_task as validate_task,
    build_error_message as build_error_message,
    validate_error as validate_error,
    build_completion_message as build_completion_message,
    validate_completion as validate_completion,
    PROTOCOL_VERSION as PROTOCOL_VERSION,
    PLAN_SCHEMA_VERSION as PLAN_SCHEMA_VERSION,
    GOLDEN_EXECUTION_ID as GOLDEN_EXECUTION_ID,
    FIXED_EXECUTION_ID as FIXED_EXECUTION_ID,
    INCREMENTAL_EXECUTION_ID as INCREMENTAL_EXECUTION_ID,
    ASYNC_EXECUTION_ID as ASYNC_EXECUTION_ID,
    MAX_INFLIGHT_TASKS as MAX_INFLIGHT_TASKS,
    ERROR_CODES as ERROR_CODES,
    Completion as Completion,
    SemanticMapPlan as SemanticMapPlan,
    PHYSICAL_ALGORITHM as PHYSICAL_ALGORITHM,
    PHYSICAL_ROLE as PHYSICAL_ROLE,
    input_utf8 as input_utf8,
    canonical_messages as canonical_messages,
    validate_completion_values as validate_completion_values,
    UINT64_MAX as UINT64_MAX,
    SEMANTIC_SPEC_ID as SEMANTIC_SPEC_ID,
    PROMPT_PROGRAM_DIGEST as PROMPT_PROGRAM_DIGEST,
    RESULT_PARSER_DIGEST as RESULT_PARSER_DIGEST,
    MAX_INPUT_BYTES as MAX_INPUT_BYTES,
    MAX_OUTPUT_BYTES as MAX_OUTPUT_BYTES,
    MAX_FRAME_BYTES as MAX_FRAME_BYTES,
    ProtocolError as ProtocolError,
    has_duplicate_fields as has_duplicate_fields,
)
